@API_HostAddress = https://localhost:5001

###
GET {{API_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

###
GET {{API_HostAddress}}/api/products?symptomIds=3&symptomIds=4&pageSize=20
Content-Type: application/json
Accept: application/json

###
GET {{API_HostAddress}}/api/products?categories=Prescription&pageSize=20
Content-Type: application/json
Accept: application/json

###
GET {{API_HostAddress}}/api/symptoms
Content-Type: application/json
Accept: application/json

###
POST {{API_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
    "Name": "Panadol Extra",
    "Description": "Relieves headaches, fever, and body aches.",
    "Price": 5.99,
    "PictureUrl": "/images/products/panadol_extra.png",
    "Type": "Tablet",
    "Brand": "GSK",
    "QuantityInStock": 100,
    "CategoryId": 1,
    "symptomIds": [1, 2]
}

###
POST {{API_HostAddress}}/api/products
Content-Type: application/json
Accept: application/json

{
    "Name": "Ibuprofen 200mg",
    "Description": "Reduces inflammation, pain, and fever.",
    "Price": 6.49,
    "PictureUrl": "/images/products/ibuprofen.png",
    "Type": "Tablet",
    "Brand": "Advil",
    "QuantityInStock": 120,
    "CategoryId": 1,
    "symptomIds": [1, 3]
}

###
POST {{API_HostAddress}}/api/symptoms
Content-Type: application/json
Accept: application/json

{
    "SymptomName": "Headache",
    "Description": "A continuous pain in the head."
}

###
POST {{API_HostAddress}}/api/symptoms
Content-Type: application/json
Accept: application/json

{
    "SymptomName": "Fever",
    "Description": "Elevated body temperature, often due to infection."
}

###
POST {{API_HostAddress}}/api/symptoms
Content-Type: application/json
Accept: application/json

{
    "SymptomName": "Cough",
    "Description": "A reflex action to clear your airways of mucus and irritants."
}

###
PUT {{API_HostAddress}}/api/products/1
Content-Type: application/json
Accept: application/json

{
    "Name": "Panadol Extra",
    "Description": "Relieves headaches, fever, and body aches.",
    "Price": 5.99,
    "PictureUrl": "/images/products/panadol_extra.png",
    "Type": "Tablet",
    "Brand": "GSK",
    "QuantityInStock": 100,
    "CategoryId": 1,
    "symptomIds": [1, 2]
}

###
POST {{API_HostAddress}}/api/account/change-role
Content-Type: application/json
Accept: application/json

{
  "email": "bob@test.com",
  "newRole": "Pharmacist"    
}
